export const ClientsConfigV1 = {
  ACCOUNTS_PORT: process.env.NEXT_PUBLIC_ACCOUNTS_PORT_V1,
  CUSTOMERS_PORT: process.env.NEXT_PUBLIC_CUSTOMERS_PORT_V1,
  LOANS_PORT: process.env.NEXT_PUBLIC_LOANS_PORT_V1,
  REQUESTS_PORT: process.env.NEXT_PUBLIC_REQUESTS_PORT_V1
};
